[custom]
;https://raw.githubusercontent.com/aplgthb/ACL4SSR/refs/heads/TV/Clash/config/APTV.ini



ruleset=📹 Youtube,https://raw.githubusercontent.com/aplgthb/ACL4SSR/refs/heads/HK/Clash/Ruleset/YouTube.list
ruleset=🐟 漏网之鱼,[]FINAL

;设置规则标志位

;设置分组标志位

custom_proxy_group=📹 Youtube`select`.*
custom_proxy_group=🐟 漏网之鱼`select`.*


;设置分组标志位

enable_rule_generator=true
overwrite_original_rules=true


;luck
